#!/bin/bash

#===============================================
# Setup the correct python environment
#===============================================
# NOTE: activate does not work correctly in Bash
# in Cygwin.
echo "Activating win virtual environment for Python"
source ".venv/Scripts/activate"
if [ $? -ne 0 ]; then
    echo "Activating virtual environment failed"
    exit 1
fi

#===============================================
# Running build for architecture
#===============================================
echo "Running build for `arch` architecure"

#===============================================
# Clean-up
#===============================================
rm -rf dist
rm -rf build

#===============================================
# Run pyinstaller
#===============================================
# Get the product version
version="`cat version`"
echo "Creating installer for version ${version}"
pyinstaller -y guitar-tap.spec
if [ $? -ne 0 ]; then
    echo "Running pyinstaller failed"
    exit 1
fi
#===============================================
# Prepare installer path
#===============================================
installer_file=`pwd`/guitar-tap.iss
ifile_win=`cygpath -w $installer_file`
ISCC_PATH="C:/Program Files (x86)/Inno Setup 6/ISCC.exe"

#===============================================
# You must install Inno Setup 6 to build the installer
#===============================================
"$ISCC_PATH" /DMyAppVersion=${version} /F $ifile_win
if [ $? -ne 0 ]; then
    echo "Creating the installer failed"
    exit 1
fi

echo "Installer created successfully"
