#!/bin/bash
#

#===============================================
# Setup the correct python environment
#===============================================
# NOTE: activate does not work correctly in Bash
# in Cygwin.
echo "Activating win virtual environment for Python"
export VIRTUAL_ENV="~/win"
export PATH="${VIRTUAL_ENV}/Scripts:${PATH}"
if [ -n "${PYTHONHOME:-}" ] ; then
    _OLD_VIRTUAL_PYTHONHOME="${PYTHONHOME:-}"
    unset PYTHONHOME
fi

echo "Running build for `arch` architecure"

#===============================================
# Clean-up
#===============================================
rm -rf dist
rm -rf build

#===============================================
# Run pyinstaller
#===============================================
# Get the product version
version="`cat version`"
echo "Creating installer for version ${version}"
pyinstaller -y guitar-tap.spec
if [ $? -ne 0 ]; then
    echo "Running pyinstaller failed"
    exit 1
fi

installer_file=`pwd`/guitar-tap.iss
ifile_win=`cygpath -w $installer_file`

#===============================================
# You must install Inno Setup 6 to build the installer
#===============================================
"c:/Program Files (x86)/Inno Setup 6"/ISCC.exe /DMyAppVersion=${version} /F $ifile_win
if [ $? -ne 0 ]; then
    echo "Creating the installer failed"
    exit 1
fi
