#!/bin/bash
#

#===============================================
# Setup the correct python environment
#===============================================
echo "Activating linux virtual environment for Python"
source ".venv/Scripts/activate"

echo "Running build for `arch` architecure"

#===============================================
# Clean-up
#===============================================
rm -rf dist
rm -rf build

#===============================================
# Run pyinstaller
#===============================================
# Get the product version
version="`cat version`"
echo "Creating installer for version ${version}"
pyinstaller -y guitar-tap.spec
if [ $? -ne 0 ]; then
    echo "Running pyinstaller failed"
    exit 1
fi
