# @parity test/pdf-report
"""A saved measurement's PDF report, as the measurement list exports it (export_report_for_measurement),
read back line by line and compared with the expected lines beside its fixture (``<fixture>.pdf.txt``):
each line's page, its height on the page and its words. A line's height is its baseline's distance from the
page's top — for a line mixing sizes, the baseline of its largest text — and must be within 1 pt of the
expected. Words are compared with whitespace removed. The measurement's date and the "Generated by …" line
are matched by position only (they depend on the locale, the time and the build). The expected lines are
Swift's; Swift PDFReportTests and the web suite have the same cases and the same expected files.
"""

from __future__ import annotations

import os
import sys
import unicodedata

import pytest

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from pypdf import PdfReader
from PySide6 import QtWidgets

from guitar_tap.utilities.date_format import format_display_datetime
from guitar_tap.views import tap_analysis_results_view as reports

TESTS = os.path.dirname(__file__)

# Each fixture, through the report its kind uses.
FIXTURES = [
    "5-guitar-comparison-1776708138",
    "annotation-override-1790037028",
    "annotation-override-python-1790037332",
    "brace-umik-1-3-tap-swift-mac-1785359380",
    "brace-umik-1-python-mac-1785442624",
    "brace-umik-1-swift-mac-1785359411",
    "comparison-long-name-1776708138",
    "contreras-classical-1774731564",
    "dws-2024-umik-1-3-tap-swift-mac-1785359425",
    "dws-2024-umik-1-3-tap-web-mac-1785440737",
    "dws-2024-umik-1-python-mac-1784225140",
    "dws-2024-umik-1-swift-mac-1784225155",
    "dws-2024-umik-1-swift-mac-1785359434",
    "dws-2024-umik-1-web-mac-1784225174",
    "plate-umik-1-3-tap-swift-ipad-1784314709",
    "plate-umik-1-3-tap-swift-mac-1785359465",
    "plate-umik-1-swift-mac-1785359486",
    "plate-umik-1-web-mac-1785440769",
]


def lines_of(path: str) -> list[tuple[int, float, str]]:
    """The pages' lines by position, as (page, baseline from the page's top, text): each text run placed by
    its matrix, grouped into lines by baseline (top to bottom), each line left to right, placed at the
    baseline of its largest run."""
    out: list[tuple[int, float, str]] = []
    for index, page in enumerate(PdfReader(path).pages):
        height = float(page.mediabox.height)
        runs: list[tuple[float, float, float, str]] = []

        def visit(text, cm, tm, _font, size):
            text = text.strip()
            if not text:
                return
            x, y = tm[4], tm[5]
            scale = (tm[2] ** 2 + tm[3] ** 2) ** 0.5 * (cm[2] ** 2 + cm[3] ** 2) ** 0.5
            runs.append((height - (x * cm[1] + y * cm[3] + cm[5]), x * cm[0] + y * cm[2] + cm[4], size * scale, text))

        page.extract_text(visitor_text=visit)
        rows: list[list[tuple[float, float, float, str]]] = []
        for run in sorted(runs, key=lambda r: r[0]):
            if rows and abs(rows[-1][0][0] - run[0]) < 3:
                rows[-1].append(run)
            else:
                rows.append([run])
        for row in rows:
            largest = row[0]
            for run in row:
                if run[2] > largest[2] + 0.01:
                    largest = run
            out.append((index, largest[0], " ".join(r[3] for r in sorted(row, key=lambda r: r[1]))))
    return out


def show(line: tuple[int, float, str]) -> str:
    return f"{line[0]}\t{line[1]:.1f}\t{line[2]}"


def squeezed(lines: list[str]) -> str:
    """The lines joined, without whitespace, in Unicode compatibility form (a ligature reads as its letters)."""
    return "".join(c for c in unicodedata.normalize("NFKC", "".join(lines)) if not c.isspace())


@pytest.fixture(scope="module", autouse=True)
def _app():
    return QtWidgets.QApplication.instance() or QtWidgets.QApplication([])


@pytest.mark.parametrize("fixture", FIXTURES)
def test_report_matches_the_expected_lines(fixture, tmp_path):
    with open(os.path.join(TESTS, fixture + ".guitartap"), "rb") as f:
        measurement = reports.measurements_from_json(f.read())[0]
    path = str(tmp_path / "report.pdf")
    reports.export_report_for_measurement(measurement, path)

    date = squeezed([format_display_datetime(measurement.timestamp)])
    actual = [
        (page, baseline,
         "<date>" if squeezed([text]) == date else "<generated>" if text.startswith("Generated by") else text)
        for page, baseline, text in lines_of(path)
    ]
    with open(os.path.join(TESTS, fixture + ".guitartap.pdf.txt"), encoding="utf-8") as f:
        expected = []
        for row in f.read().splitlines():
            page, baseline, text = row.split("\t", 2)
            expected.append((int(page), float(baseline), text))
    listing = (f"{fixture}:\n--- actual\n" + "\n".join(map(show, actual))
               + "\n--- expected\n" + "\n".join(map(show, expected)))
    assert len(actual) == len(expected), f"line count {len(actual)} != {len(expected)}\n{listing}"
    for a, e in zip(actual, expected):
        assert (a[0] == e[0] and abs(a[1] - e[1]) <= 1 and squeezed([a[2]]) == squeezed([e[2]])), (
            f"{show(a)} != expected {show(e)}\n{listing}")
