#!/bin/bash
#

# Run from the project root regardless of where this script is invoked from.
cd "$(dirname "$0")/.."

#===============================================
# Setup the correct python environment
#===============================================
echo "Activating linux virtual environment for Python"
source ".venv/Scripts/activate"

echo "Running build for `arch` architecure"

#===============================================
# Clean-up
#===============================================
rm -rf dist
rm -rf build

#===============================================
# Generate version_build from git commit count
#===============================================
./packaging/gen_version_build.sh
if [ $? -ne 0 ]; then
    echo "Generating version_build failed"
    exit 1
fi

#===============================================
# Run pyinstaller
#===============================================
# Get the product version
version="`cat src/guitar_tap/version`"
echo "Creating installer for version ${version}"
pyinstaller -y packaging/guitar-tap.spec
if [ $? -ne 0 ]; then
    echo "Running pyinstaller failed"
    exit 1
fi
