# -*- mode: python ; coding: utf-8 -*-

import sys
import platform
added_binaries = []
if sys.platform == 'darwin':
    if platform.machine() == 'x86_64':
        added_binaries = [ ('/Users/dws/portaudio/lib/libportaudio.2.dylib', '.') ]
        
with open(os.path.abspath('./src/guitar_tap/version'), 'r') as f:
    version = f.read().strip()

# 'version_build' is generated by the CI script: git rev-list --count HEAD > src/guitar_tap/version_build
# It is not committed to git; when absent (dev builds) it is omitted.
import os as _os
build_file = os.path.abspath('./src/guitar_tap/version_build')
build = open(build_file).read().strip() if _os.path.exists(build_file) else ''

print(f'Creating build for version {version} build {build or "(dev)"}')

block_cipher = None

added_files = [
    ('src/guitar_tap/icons/guitar-tap.ico', '.'),
    ('src/guitar_tap/icons','icons'),
    ('src/guitar_tap/version', '.'),
    ]

# Bundle 'version_build' file only if it exists (CI builds).
if _os.path.exists(build_file):
    added_files.append(('src/guitar_tap/version_build', '.'))

a = Analysis(
    ['src/guitar_tap/__main__.py'],
    pathex=['src/guitar_tap'],
    binaries=added_binaries,
    datas=added_files,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='guitar-tap',
    icon='src/guitar_tap/icons/guitar-tap.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity='Developer ID Application: David Smith (43QHHT3XK2)',
    entitlements_file='packaging/entitlements.plist',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='guitar-tap',
)

package_version = f'{version}.0'
bundle_version = build if build else package_version  # build number or fallback

app = BUNDLE(coll,
    name='Guitar Tap.app',
    icon='src/guitar_tap/icons/guitar-tap.icns',
    version=package_version,
    bundle_identifier='com.dolcesfogato.guitar-tap',
    info_plist={
      'CFBundleName': 'Guitar Tap',
      'CFBundleDisplayName': 'Guitar Tap',
      'CFBundleVersion': bundle_version,          # build number (e.g. "47")
      'CFBundleShortVersionString': package_version,  # marketing version (e.g. "0.11.0")
      'NSPrincipalClass': 'NSApplication',
      'NSAppleScriptEnabled': False,
      'NSRequiresAquaSystemAppearance': 'No',
      'NSHighResolutionCapable': 'True',
      'NSMicrophoneUsageDescription': 'Guitar Tap from the audio inputs to show spectrum and peaks'
    },
)
