# -*- mode: python ; coding: utf-8 -*-

import os
import sys
import platform

# Resolve the project root relative to this spec file's location (packaging/).
project_root = os.path.abspath(os.path.join(SPECPATH, '..'))

added_binaries = []
if sys.platform == 'darwin':
    if platform.machine() == 'x86_64':
        added_binaries = [ ('/Users/dws/portaudio/lib/libportaudio.2.dylib', '.') ]

with open(os.path.join(project_root, 'src/guitar_tap/version'), 'r') as f:
    version = f.read().strip()

# 'version_build' is generated by gen_version_build.sh (git rev-list --count HEAD).
# It is not committed to git; when absent (dev builds) it defaults to '0'.
build_file = os.path.join(project_root, 'src/guitar_tap/version_build')
build = open(build_file).read().strip() if os.path.exists(build_file) else '0'

# Full version string: e.g. "1.0.245"
package_version = f'{version}.{build}'

print(f'Creating build for version {package_version}')

added_files = [
    (os.path.join(project_root, 'src/guitar_tap/icons/guitar-tap.ico'), '.'),
    (os.path.join(project_root, 'src/guitar_tap/icons'), 'icons'),
    (os.path.join(project_root, 'src/guitar_tap/version'), '.'),
]

# Bundle 'version_build' file only if it exists (CI builds).
if os.path.exists(build_file):
    added_files.append((build_file, '.'))

a = Analysis(
    [os.path.join(project_root, 'src/guitar_tap/__main__.py')],
    pathex=[os.path.join(project_root, 'src/guitar_tap')],
    binaries=added_binaries,
    datas=added_files,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe_args = [pyz, a.scripts, []]

exe = EXE(
    *exe_args,
    exclude_binaries=True,
    name='guitar-tap',
    icon=os.path.join(project_root, 'src/guitar_tap/icons/guitar-tap.ico'),
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity='Developer ID Application: David Smith (43QHHT3XK2)',
    entitlements_file=os.path.join(SPECPATH, 'entitlements.plist'),
)

collect_args = [exe, a.binaries, a.datas]

coll = COLLECT(
    *collect_args,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='guitar-tap',
)

app = BUNDLE(coll,
    name='Guitar Tap.app',
    icon=os.path.join(project_root, 'src/guitar_tap/icons/guitar-tap.icns'),
    version=package_version,
    bundle_identifier='com.dolcesfogato.guitar-tap',
    info_plist={
      'CFBundleName': 'Guitar Tap',
      'CFBundleDisplayName': 'Guitar Tap',
      'CFBundleVersion': package_version,          # e.g. "1.0.245"
      'CFBundleShortVersionString': package_version,  # e.g. "1.0.245"
      'NSPrincipalClass': 'NSApplication',
      'NSAppleScriptEnabled': False,
      'NSRequiresAquaSystemAppearance': 'No',
      'NSHighResolutionCapable': 'True',
      'NSMicrophoneUsageDescription': 'Guitar Tap from the audio inputs to show spectrum and peaks'
    },
)
